# Copyright (C) 2021, Yubao Liu, AISL, TOYOHASHI UNIVERSITY of TECHNOLOGY 
# Email: yubao.liu.ra@tut.jp 
version: '2.3'
services:
  okvis_ros:
    image: yubao/okvis_ros
    build:
        context: .
        # container_name: okvis_ros
        # args:
        #     - HTTP_PROXY=$HTTP_PROXY
        #     - http_proxy=$HTTP_PROXY
        #     - HTTPS_PROXY=$HTTPS_PROXY
        #     - https_proxy=$HTTPS_PROXY
    command:  lxterminal
    runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ..:/home/ubuntu/catkin_ws/src/okvis_ros
        - ${DATASET_DIR}:/home/ubuntu/dataset
        - ~/.vim:/home/ubuntu/.vim
        # - ./extern:/home/ubuntu/extern
    entrypoint: /ros_entrypoint.sh
    network_mode: host
    dns:
        - 8.8.8.8
        - 4.4.4.4

# volumes:
#     okvis_ros_root:
